AllCops:
  NewCops: enable

plugins:
  - rubocop-minitest
  - rubocop-rails

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
